Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/004-SFARI-compcorr-filter.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/data_preprocessed_sfari-run1_notebooks/27-run2-sfari-compcorr.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmppf69nw1b'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmp70k2v9t6'
Executing:   0%|          | 0/70 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   1%|▏         | 1/70 [00:05<06:36,  5.75s/cell]Executing:   4%|▍         | 3/70 [00:33<09:06,  8.15s/cell]Executing:   7%|▋         | 5/70 [00:33<06:12,  5.73s/cell]Executing:  10%|█         | 7/70 [00:35<04:30,  4.29s/cell]Executing:  13%|█▎        | 9/70 [00:35<03:04,  3.02s/cell]Executing:  16%|█▌        | 11/70 [00:35<02:06,  2.14s/cell]Executing:  19%|█▊        | 13/70 [00:35<01:26,  1.52s/cell]Executing:  21%|██▏       | 15/70 [00:35<00:59,  1.09s/cell]Executing:  24%|██▍       | 17/70 [00:42<01:29,  1.69s/cell]Executing:  27%|██▋       | 19/70 [00:42<01:01,  1.21s/cell]Executing:  30%|███       | 21/70 [00:42<00:42,  1.15cell/s]Executing:  33%|███▎      | 23/70 [00:42<00:29,  1.58cell/s]Executing:  36%|███▌      | 25/70 [00:42<00:21,  2.14cell/s]Executing:  39%|███▊      | 27/70 [00:42<00:15,  2.85cell/s]Executing:  41%|████▏     | 29/70 [00:43<00:14,  2.88cell/s]Executing:  43%|████▎     | 30/70 [00:43<00:12,  3.27cell/s]Executing:  46%|████▌     | 32/70 [00:43<00:09,  4.18cell/s]Executing:  47%|████▋     | 33/70 [00:47<00:44,  1.20s/cell]Executing:  49%|████▊     | 34/70 [00:50<01:02,  1.74s/cell]Executing:  49%|████▊     | 34/70 [00:53<00:56,  1.58s/cell]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [25]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-ed678b2a363d> in <module>
----> 1 rfmat_nii = filt(im=rmat_nii,tr=data['tr'],lowf=.01,highf=.1,order=3)
      2 srfmat_nii = ants.smooth_image(image=rfmat_nii,sigma=4,sigma_in_physical_coordinates=True,FWHM=True,max_kernel_width=32)

<ipython-input-18-24fc9497fa79> in filt(im, tr, lowf, highf, order)
      1 def filt(im,tr,lowf=.01,highf=.1,order=3):
----> 2     imfilt = ants.bandpass_filter_matrix(im,tr=tr, lowf=lowf, highf=highf, order=order)
      3     return imfilt

~/anaconda3/lib/python3.8/site-packages/ants/utils/quantile.py in bandpass_filter_matrix(matrix, tr, lowf, highf, order)
    288     matrixOut = matrix.copy()
    289     for k in range( ncolumns ):
--> 290         matrixOut[:,k] = butter_bandpass_filter(
    291             matrix[:,k], lowf, highf, fs, order=order )
    292     return matrixOut

~/anaconda3/lib/python3.8/site-packages/ants/utils/quantile.py in butter_bandpass_filter(data, lowcut, highcut, fs, order)
    280     def butter_bandpass_filter(data, lowcut, highcut, fs, order ):
    281         b, a = butter_bandpass(lowcut, highcut, fs, order=order)
--> 282         y = filtfilt(b, a, data)
    283         return y
    284 

~/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py in filtfilt(b, a, x, axis, padtype, padlen, method, irlen)
   3891 
   3892     # method == "pad"
-> 3893     edge, ext = _validate_pad(padtype, padlen, x, axis,
   3894                               ntaps=max(len(a), len(b)))
   3895 

~/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py in _validate_pad(padtype, padlen, x, axis, ntaps)
   3941     # x's 'axis' dimension must be bigger than edge.
   3942     if x.shape[axis] <= edge:
-> 3943         raise ValueError("The length of the input vector x must be greater "
   3944                          "than padlen, which is %d." % edge)
   3945 

ValueError: The length of the input vector x must be greater than padlen, which is 21.

