Input Notebook:  /data/aglinska/BC-fMRI-AE/Notebooks/004-SFARI-compcorr-filter.ipynb
Output Notebook: /data/aglinska/BC-fMRI-AE/Assets/data_preprocessed_sfari-run1_notebooks/182-run2-sfari-compcorr.ipynb
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmpnrj8sdlb'
Generating grammar tables from /data/aglinska/anaconda3/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /data/aglinska/.cache/black/21.8b0/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/data/aglinska/.cache/black/21.8b0/tmpjjmnw7ks'
Executing:   0%|          | 0/70 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   1%|▏         | 1/70 [00:05<06:35,  5.73s/cell]Executing:   4%|▍         | 3/70 [00:46<11:20, 10.16s/cell]Executing:   7%|▋         | 5/70 [00:46<07:43,  7.13s/cell]Executing:  10%|█         | 7/70 [00:48<05:26,  5.19s/cell]Executing:  13%|█▎        | 9/70 [00:48<03:42,  3.65s/cell]Executing:  16%|█▌        | 11/70 [00:48<02:31,  2.57s/cell]Executing:  19%|█▊        | 13/70 [00:48<01:43,  1.82s/cell]Executing:  21%|██▏       | 15/70 [00:48<01:10,  1.29s/cell]Executing:  24%|██▍       | 17/70 [00:53<01:24,  1.60s/cell]Executing:  27%|██▋       | 19/70 [00:53<00:57,  1.13s/cell]Executing:  30%|███       | 21/70 [00:53<00:39,  1.23cell/s]Executing:  33%|███▎      | 23/70 [00:53<00:27,  1.71cell/s]Executing:  36%|███▌      | 25/70 [00:53<00:19,  2.34cell/s]Executing:  39%|███▊      | 27/70 [00:53<00:13,  3.16cell/s]Executing:  41%|████▏     | 29/70 [00:54<00:12,  3.37cell/s]Executing:  44%|████▍     | 31/70 [00:54<00:09,  3.99cell/s]Executing:  47%|████▋     | 33/70 [00:57<00:23,  1.60cell/s]Executing:  49%|████▊     | 34/70 [00:59<00:39,  1.08s/cell]Executing:  49%|████▊     | 34/70 [01:01<01:05,  1.81s/cell]
Traceback (most recent call last):
  File "/data/aglinska/anaconda3/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/data/aglinska/anaconda3/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [25]":
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-ed678b2a363d> in <module>
----> 1 rfmat_nii = filt(im=rmat_nii,tr=data['tr'],lowf=.01,highf=.1,order=3)
      2 srfmat_nii = ants.smooth_image(image=rfmat_nii,sigma=4,sigma_in_physical_coordinates=True,FWHM=True,max_kernel_width=32)

<ipython-input-18-24fc9497fa79> in filt(im, tr, lowf, highf, order)
      1 def filt(im,tr,lowf=.01,highf=.1,order=3):
----> 2     imfilt = ants.bandpass_filter_matrix(im,tr=tr, lowf=lowf, highf=highf, order=order)
      3     return imfilt

~/anaconda3/lib/python3.8/site-packages/ants/utils/quantile.py in bandpass_filter_matrix(matrix, tr, lowf, highf, order)
    288     matrixOut = matrix.copy()
    289     for k in range( ncolumns ):
--> 290         matrixOut[:,k] = butter_bandpass_filter(
    291             matrix[:,k], lowf, highf, fs, order=order )
    292     return matrixOut

~/anaconda3/lib/python3.8/site-packages/ants/utils/quantile.py in butter_bandpass_filter(data, lowcut, highcut, fs, order)
    280     def butter_bandpass_filter(data, lowcut, highcut, fs, order ):
    281         b, a = butter_bandpass(lowcut, highcut, fs, order=order)
--> 282         y = filtfilt(b, a, data)
    283         return y
    284 

~/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py in filtfilt(b, a, x, axis, padtype, padlen, method, irlen)
   3891 
   3892     # method == "pad"
-> 3893     edge, ext = _validate_pad(padtype, padlen, x, axis,
   3894                               ntaps=max(len(a), len(b)))
   3895 

~/anaconda3/lib/python3.8/site-packages/scipy/signal/signaltools.py in _validate_pad(padtype, padlen, x, axis, ntaps)
   3941     # x's 'axis' dimension must be bigger than edge.
   3942     if x.shape[axis] <= edge:
-> 3943         raise ValueError("The length of the input vector x must be greater "
   3944                          "than padlen, which is %d." % edge)
   3945 

ValueError: The length of the input vector x must be greater than padlen, which is 21.

